version: '3'
services:    
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - influx_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=greatname
      - DOCKER_INFLUXDB_INIT_PASSWORD=supersecretpass
      - DOCKER_INFLUXDB_INIT_ORG=myorg  
      - DOCKER_INFLUXDB_INIT_BUCKET=home_assistant
      - DOCKER_INFLUXDB_INIT_RETENTION=30d  
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana        
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=greatname
      - GF_SECURITY_ADMIN_PASSWORD=supersecretpass
volumes:
  influx_data:      
  grafana_data:
