apiVersion: 1

datasources:
  - name: Home Assistant
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: $INFLUXDB_TOKEN
    jsonData:
      version: Flux
      organization: $INFLUXDB_ORG
      defaultBucket: home_assistant
      tlsSkipVerify: true
