apiVersion: 1

datasources:
  - name: Home Assistant
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: mytoken
    jsonData:
      version: Flux
      organization: myorg
      defaultBucket: home_assistant
      tlsSkipVerify: true
